retrofit-drupal/retrofit

phpstan-baseline.neon
src/Language/GlobalLanguageContent.php
src/Language/GlobalLanguageContentSetter.php
src/Provider.php
tests/src/Integration/Language/GlobalLanguageContentTest.php

Support global $language_content variable

---

phpstan-baseline.neon
src/Provider.php
src/Render/AttachmentResponseSubscriber.php
src/functions/common.php
tests/data/retrofit_fixtures/retrfofit_fixtures.info.yml
tests/data/retrofit_fixtures/retrofit_fixtures.module
tests/src/Integration/Render/AttachmentResponseSubscriberTest.php

drupal_add_library support

---

phpstan-baseline.neon
src/Render/RetrofitHtmlResponseAttachmentsProcessor.php
src/functions/common.php
tests/data/retrofit_fixtures/retrofit_fixtures.module
tests/src/Integration/Render/AttachmentResponseSubscriberTest.php

Drupal.settings support

---

src/functions.php
src/functions/user.php
tests/src/Unit/UserTest.php

user_is_anonymous, user_is_logged_in replacement

---

src/functions/common.php

Spins out `filter_xss_admin` and friends from #32

Add filter_xss_admin, filter_xss, filter_xss_bad_protocol

---

src/functions/common.php
tests/src/Unit/Render/AttachmentResponseSubscriberTest.php

Spins drupal_add_css out of #32

Add drupal_add_css

---

phpstan-baseline.neon
src/functions.php
src/functions/module.php
tests/src/Integration/ModuleTest.php

Add module_exists

---

src/functions/theme.php

Spins path_to_theme out of #32

Add path_to_theme

---

phpstan-baseline.neon
src/functions/variable.php
tests/src/Integration/VariablesTest.php

Add site_name and site_slogan support to variable_get

---

.github/workflows/ci.yml
src/Theme/Registry.php
tests/data/retrofit_fixtures/retrofit_fixtures.module
tests/src/Integration/Template/HookProcessTest.php

Collect process hooks as preprocess functions

---

src/functions/cache.php
tests/src/Unit/Functions/CacheTest.php

- Fix default cache
- add unit test
https://github.com/retrofit-drupal/retrofit/pull/63/commits/72b17ad47c77f3622884fc79951e6870282193b9 from https://github.com/retrofit-drupal/retrofit/pull/63

Fix default cache bin

---

src/Field/FieldTypePluginManager.php

Temporary hack to keep #71 from crashing site.

Temporary fix for EntityReferenceItem

---

src/functions/db.php
tests/src/Integration/Database/DbTest.php

From https://github.com/retrofit-drupal/retrofit/pull/63/commits/d15f7feb13c915e92dc406c9e7e7308ed521672c in https://github.com/retrofit-drupal/retrofit/pull/63

Add db_table_exists()

---

src/functions/user.php
tests/src/Unit/UserTest.php

From https://github.com/retrofit-drupal/retrofit/pull/63 with https://github.com/retrofit-drupal/retrofit/pull/63/commits/ca4b6c778a747766606f1bf57caf0b23179fc054

Add user_access()

---

src/functions.php
src/functions/lock.php
tests/src/Unit/LockTest.php
tests/src/Unit/UserTest.php

From https://github.com/retrofit-drupal/retrofit/pull/63
* https://github.com/retrofit-drupal/retrofit/pull/63/commits/cc7d6caaa6c573a776d654b08233b73f4d51cef2
* https://github.com/retrofit-drupal/retrofit/pull/63/commits/4cc96d4267917e76f2a938ad3a5eaebcceaea20a

Add lock_acquia and lock_release

---

phpstan-baseline.neon
src/Controller/RetrofitTitleResolver.php
src/Provider.php
src/functions/bootstrap.php
tests/data/retrofit_fixtures/retrofit_fixtures.module
tests/src/Integration/RetrofitTitleResolverTest.php

Splits out from https://github.com/retrofit-drupal/retrofit/pull/63 with flushed out support

Add drupal_set_title/drupal_get_title

---

phpstan-baseline.neon
src/functions/messages.php
tests/src/Integration/DrupalSetMessageTest.php

Split from https://github.com/retrofit-drupal/retrofit/pull/63

Improve drupal_set_message

---

src/functions/bootstrap.php

From https://github.com/retrofit-drupal/retrofit/pull/63

Improve drupal_get_schema

---

phpstan-baseline.neon
src/Render/RetrofitHtmlResponseAttachmentsProcessor.php

Split from https://github.com/retrofit-drupal/retrofit/pull/63

Add is_array check in response attachment processor

---

src/functions/common.php

From https://github.com/retrofit-drupal/retrofit/pull/63

Add drupal_map_assoc

---

src/functions/common.php

Add drupal_clean_css_identifier

---

src/functions/common.php

Split from #63 
- Add drupal_array_get_nested_value
- add set and key exists

Add nested array functions

---

src/functions/common.php

Add drupal_get_library

---

src/functions/common.php

Add drupal_goto

---

src/functions/bootstrap.php
src/functions/common.php
tests/src/Integration/Database/DrupalWriteRecordTest.php

- Add drupal_write_record
- rewrite drupal_write_record to match D7

Add drupal_write_record

---

phpstan-baseline.neon
src/Form/ArrayAccessFormState.php
src/Form/FormBuilder.php
src/functions/form.php

I encountered this when working with views exposed filters.

Fix missing protected form state properties

---

composer.json
phpstan-baseline.neon
phpstan.neon.dist
src/functions/common.php
tests/bootstrap.php

recreated https://github.com/retrofit-drupal/retrofit/pull/94 without extra fixes.

Add phpstan-drupal

---

.github/workflows/ci.yml
tests/bootstrap.php
tests/src/Unit/UserTest.php

Test only fixes, not bumping the minimum required version.
Fixes #140

Fix 10.2.0 compatibility

---

phpstan-baseline.neon
src/Theme/HookPreprocess.php

not the best fix, but removes warning
fixes #147

fix indirect modification of overloaded element

---

src/EventSubscriber/HookExit.php
src/Provider.php
tests/data/retrofit_fixtures/retrofit_fixtures.module
tests/src/Integration/HookExitTest.php

Add hook_exit subscriber

---

src/EventSubscriber/HookInit.php
src/Provider.php
tests/data/retrofit_fixtures/retrofit_fixtures.module
tests/src/Integration/HookExitTest.php
tests/src/Integration/HookInitTest.php

Add hook_init support

---

phpstan-baseline.neon
src/Controller/DrupalGetFormController.php
src/Form/ArrayAccessFormState.php
tests/src/Integration/Routing/HookMenuFormRoutesTest.php

Add include file to form state build info

---

phpstan-baseline.neon
src/Form/ArrayAccessFormState.php
tests/src/Integration/IntegrationTestCase.php
tests/src/Unit/UserTest.php
tests/src/Utils/TestModuleExtensionList.php
tests/src/Utils/TestModuleHandler.php

Support build_info in form state decoration
